using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Funcionamiento : MonoBehaviour
{
    [SerializeField] private float speed = 7f;
    [SerializeField] private bool PrimerPlayer;
    private float yBound = 3.75f;
    // Start is called before the first frame update
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {
        float movement;
        if (PrimerPlayer)
        {
            movement = Input.GetAxisRaw("Vertical");
        }
        else
        {
            movement = Input.GetAxisRaw("Vertical 2");
        }

        Vector2 paddlePosition = transform.position;
        paddlePosition.y = Mathf.Clamp(paddlePosition.y + movement * speed * Time.deltaTime, -yBound, yBound);
        transform.position = paddlePosition;
    }
}
